### ISSUE TITLE
Allow reading PBR textures by suffix

### ISSUE THREAD

**Issue by janhohenheim** [Noxmore/bevy_materialize#2]
Opening this up so it doesn't get lost :)

When downloading PBR textures online or creating them yourself, you will nearly always have a normal map, very often a roughness and metallic map, sometimes ambient occlusion and displacement textures as well. With the current workflow, I need to do something like this to all my materials:

```toml
# rock_wall_13_1k.material
[material]
base_color_texture = "rock_wall_13_1k.png"
occlusion_texture = "rock_wall_13_1k/rock_wall_13_arm_1k.png"
metallic_roughness_texture = "rock_wall_13_1k/rock_wall_13_arm_1k.png"
normal_map_texture = "rock_wall_13_1k/rock_wall_13_nor_dx_1k.png"
depth_map = "rock_wall_13_1k/rock_wall_13_disp_1k.png"
```

As you can see, this is pretty much just boilerplate. It would be nicer to have something like [Qodot's automatic texture loading](
https://qodotplugin.github.io/docs/materials.html#automatic-pbr-texturing), which searches for things like `foo_normal.png` automatically when you load a `foo.png`. 

Alternatively, a way to autogenerate this boilerplate would be nice.

**Comment by Noxmore** [comment]
I have a few ideas for possible APIs:

## Add on to `SimpleGenericMaterialLoader`
The API would change to allow you to load any assets for your material, rather than just handing you a single `Handle<Image>`.

Pros
- 1 less file per material if it is a `StandardMaterial` (or whatever the user has configured)

Cons
- Boilerplate returns if you need to switch to full material files
- Further complicates the API, "Simple" *is* in the name

## Code hook
Some sort of hook that runs when a `GenericMaterial` is loaded, you could then set the appropriate textures if they exist and aren't defined already.

Pros
- Works for any `GenericMaterial` asset loader

Cons
- Sort of hides functionality

## Default material/inheritance
A "super-material" of sort that materials can inherit from, perhaps it could look like this
```toml
# super-material.toml
[material]
base_color_texture = "${name}.png"
occlusion_texture = "${name}_ao.png"
metallic_roughness_texture = "${name}_mr.png"
normal_map_texture = "${name}_normal.png"
depth_map = "${name}_depth.png"
```
`${name}` would be automatically replaced with the material's name (not including file extension)

Then a sub-material could somehow specify that it inherits this
```toml
inherits = "super-material.toml"

[material]
base_color_texture = "my-other-thing.png" # Overwrite values if you want to
```
The only thing this doesn't account for is if not all of these textures exist, perhaps we could have a way to mark textures optional?
```toml
base_color_texture = { path = "${name}.png", optional = true }
# or
base_color_texture = { optional = "${name}.png" }
```

Pros
- Not hardcoded, artists would probably prefer this

Cons
- Honestly i can't really think of any, having a hardcoded replacement pattern feels a little unappetizing to me but comparing with the alternatives it isn't that bad

## Pre-generate
Either with a build script or asset processing.

Pros
- Best runtime loading performance, as we only need to check if images exist at build time (though the speed gain is probably trivial)

Cons
- Doesn't actually solve the boilerplate

# My thoughts
As you might be able to tell, i'm leaning towards the inheritance route.

I'm quite cautious to keep the API as simple and intuitive as possible, but i feel like this would improve the developer experience enough to sacrifice a little of that.
